# Generated by Django 3.1.2 on 2021-06-01 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('otros_nombres', models.TextField(blank=True, null=True)),
                ('datos', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Raw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cf', models.TextField(blank=True, db_index=True, null=True)),
                ('anio', models.TextField(blank=True, db_index=True, null=True)),
                ('datos', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('f_pond', models.FloatField(blank=True, null=True)),
                ('eval_inst', models.IntegerField(blank=True, null=True)),
                ('edad', models.TextField(blank=True, null=True)),
                ('sexo', models.TextField(blank=True, null=True)),
                ('habilitado', models.TextField(blank=True, null=True)),
                ('datos', models.JSONField(default=dict)),
                ('institucion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.institucion')),
            ],
        ),
    ]
