# Generated by Django 3.1.2 on 2021-06-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='experiencia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
