# Generated by Django 3.1.2 on 2021-06-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_respuesta_experiencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='educacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
