# Generated by Django 3.1.2 on 2021-06-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210601_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='PEC_eval_presencial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='PEC_eval_telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='PEC_eval_web',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
