# Generated by Django 3.1.2 on 2021-06-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210603_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='pi_imagen_confianza',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
