# Generated by Django 3.1.2 on 2021-06-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_respuesta_pi_imagen_confianza'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='pec_canal_presencial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='pec_canal_telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='pec_canal_web',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
