# Generated by Django 3.1.2 on 2021-06-04 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20210603_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='tipo_tramite',
            field=models.TextField(blank=True, null=True),
        ),
    ]
