# Generated by Django 3.1.2 on 2021-06-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_respuesta_tipo_tramite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='anio',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
