# Generated by Django 3.1.2 on 2021-06-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20210603_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='resumen',
            field=models.JSONField(default=dict),
        ),
    ]
