# Generated by Django 3.1.2 on 2022-01-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_institucion_resumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='codigo_dipres',
            field=models.TextField(blank=True, null=True),
        ),
    ]
