# Generated by Django 3.1.2 on 2022-01-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_institucion_codigo_dipres'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='nombre_corto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
