# Generated by Django 3.1.2 on 2022-01-07 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_institucion_nombre_corto'),
    ]

    operations = [
        migrations.AddField(
            model_name='raw',
            name='institucion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.institucion'),
        ),
    ]
